countries/urls.py
from django.urls import path
from .views import BusinessView

app_name = 'country'

urlpatterns = [
    path('business/', BusinessView.as_view(), name='business',)
]

events/urls.py
from django.urls import path

from .views import EventView


app_name = 'events'

urlpatterns = [
    path('all/', EventView.as_view(), name='all')
]

information/urls.py
from django.urls import path

from .views import ContactUsMessageView, AboutUsView, QualityStandardView


app_name = 'information'

urlpatterns = [
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('contact-us/', ContactUsMessageView.as_view(), name='contact_us'),
    path('quality-standards/', QualityStandardView.as_view(), name='quality_standard'),
]

seven_sky/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import HomePage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('information.urls', namespace='info')),
    path('events/', include('events.urls', namespace='events')),
    path('products/', include('products.urls', namespace='products')),
    path('countries/', include('countries.urls', namespace='countries')),
    path('', HomePage.as_view(), name='home')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" integrity="sha512-OTcub78R3msOCtY3Tc6FzeDJ8N9qvQn1Ph49ou13xgA9VsH9+LRxoFU6EqLhW4+PKRfU+/HReXmSZXHEkpYoOA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'images/seven_sky_logo.png' %}"/>

templates/base/footer.html
<footer>
    <div class="container">
        <div class="row footer-section">
            <ul class="nav justify-content-center py-3">
                <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">HOME</a></li>
                <li class="nav-item"><a href="{% url 'info:about_us' %}" class="nav-link">About Us</a></li>
                <li class="nav-item"><a href="{% url 'events:all' %}" class="nav-link">News & Events</a></li>
                <li class="nav-item"><a href="{% url 'products:all' %}" class="nav-link">Products</a></li>
                <li class="nav-item"><a href="{% url 'countries:business' %}" class="nav-link">Business</a></li>
<!--                <li class="nav-item"><a href="#" class="nav-link">Gallery</a></li>-->
                <li class="nav-item"><a href="{% url 'info:quality_standard' %}" class="nav-link">Quality Standards</a></li>
                <li class="nav-item"><a href="{% url 'info:contact_us' %}" class="nav-link">Contact Us</a></li>
            </ul>
            <p class="nav-text text-center pt-3">Copyright 2021 © SevenSky Group.</p>
            <div class="footer-icons text-center py-2">
                <a href="{{ main_info.facebook }}" class="px-2"><i class="fab fa-facebook"></i></a>
                <a href="{{ main_info.instagram }}" class="px-2"><i class="fab fa-instagram"></i></a>
                <a href="{{ main_info.twitter }}" class="px-2"><i class="fab fa-twitter"></i></a>
                <a href="{{ main_info.linkedin }}" class="px-2"><i class="fab fa-linkedin"></i></a>
                <a href="{{ main_info.youtube }}" class="px-2"><i class="fab fa-youtube"></i></a>
                <a href="https://wa.me/+{{ main_info.whatsapp }}" class="px-2"><i class="fab fa-whatsapp"></i></a>
            </div>
        </div>
    </div>
</footer>

templates/base/js.html
{% load static %}
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"  integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="  crossorigin=""></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

templates/base/nav.html
<nav class="navbarr fixed-top" style="zoom: 75%">
    <div class="brand">
        <a href="#" style="zoom: 125%">SEVEN SKY</a>
    </div>
    <button class="toggle-button">
        <span class="toggler-icon top-bar"></span>
        <span class="toggler-icon middle-bar"></span>
        <span class="toggler-icon bottom-bar"></span>
    </button>
    <div class="navbarr-links">
        <ul id="myDIV">
            <li><a href="#home" class="navLink active"> HOME </a></li>
            <li><a href="#about" class="navLink">About Us</a></li>
            <li><a href="#news" class="navLink">News & Events</a></li>
            <li><a href="#products" class="navLink">Products</a></li>
            <li><a href="#business" class="navLink">Business</a></li>
            <li><a href="#gallery" class="navLink">Gallery</a></li>
            <li><a href="#quality" class="navLink">Quality Standers</a></li>
            <li><a href="{% url 'info:contact_us' %}" class="nav-link">Contact Us</a></li>
<!--            {% if request.user.is_authenticated and request.user.is_superuser %}-->
<!--            <li><a href="{% url 'admin:index' %}" class="navLink">Admin</a></li>-->
<!--            {% else %}-->
<!--            <li><a href="{% url 'admin:login' %}" class="navLink">LogIn</a></li>-->
<!--            {% endif %}-->
            <li class="nav-butn">
                <button>
                    <i class="fas fa-globe"></i>
                    <input class="btn message-send" type="submit" value="EN">
                </button>
            </li>
        </ul>
    </div>
</nav>